services:
  #SpringBoot 앱을 Docker 이미지로 빌드.
  app: #App 컨테이너
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deliver-app
    depends_on: #아래 항목들이 먼저 실행된 후, Spring Boot 실행.
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      #App과 mysql 컨테이너 연결
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/deliver?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: deliver
      SPRING_DATASOURCE_PASSWORD: deliver
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      #App Redis 컨테이너 연결
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: change-this-jwt-secret-key-for-docker-env-only-32chars+
      JWT_ACCESS_TOKEN_EXPIRATION_MS: 3600000
      JWT_REFRESH_TOKEN_EXPIRATION_MS: 1209600000
      #Toss 테스트 키 환경변수 전달
      TOSS_CLIENT_KEY: ${TOSS_CLIENT_KEY}
      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}

    ports:
      - "8080:8080"
    restart: unless-stopped

  mysql: #mysql 컨테이너
    image: mysql:8.0
    container_name: deliver-mysql
    environment:
      MYSQL_DATABASE: deliver
      MYSQL_USER: deliver
      MYSQL_PASSWORD: deliver
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"   #3306은 로컬mysql에서 사용중, 3307은 다른 프로젝트 docker에서 사용중.
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  redis: #Redis 컨테이너
    image: redis:7
    container_name: deliver-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  mysql-data: